Repository opendevstack/ods-project-quickstarters, pull requests merged in 2019-08, with the labels that each got.

#303 Fix company mention
  boilerplates/fe-ionic/files/README.md
Labels: documentation

#300 Create junit test report for golang quickstarter
  boilerplates/be-golang/Jenkinsfile
  jenkins-slaves/golang/Dockerfile.rhel7
Labels: enhancement

#313 fixes #ods-jenkins-shared-library/issues/109
  ocp-templates/scripts/clone-project.sh
Labels: bug

#308 Install java-11-openjdk
  boilerplates/be-springboot/files/docker/Dockerfile
  boilerplates/be-springboot/templates/build-4.10.gradle
  jenkins-slaves/maven/Dockerfile.rhel7
Labels: enhancement

#306 Airflow QuickStarter
  boilerplates/airflow/Airflow Architecture Diagram.png
  boilerplates/airflow/Jenkinsfile
  boilerplates/airflow/README.md
  boilerplates/airflow/custom-create-components.sh
  boilerplates/airflow/files/build.sh
  boilerplates/airflow/files/docker/Dockerfile
  boilerplates/airflow/files/docker/scripts/setup.py
  boilerplates/airflow/files/src/dag_deps/.keep
  boilerplates/airflow/files/src/dag_deps/dag_deps_package/__init__.py
  boilerplates/airflow/files/src/dag_deps/dag_deps_package/crazy_python.py
  boilerplates/airflow/files/src/dags/.keep
  boilerplates/airflow/files/src/dags/hello_dag.py
  boilerplates/airflow/files/src/dags/hello_kubernetes_operator.py
  boilerplates/airflow/files/src/dags/hello_python_dag.py
  boilerplates/airflow/files/src/requirements.txt
  boilerplates/airflow/files/test_all.sh
  boilerplates/airflow/files/test_dag_integrity.sh
  boilerplates/airflow/files/tests/dag_deps/.keep
  boilerplates/airflow/files/tests/dag_deps/__init__.py
  boilerplates/airflow/files/tests/dag_deps/test_crazy_python.py
  boilerplates/airflow/files/tests/dags/__init__.py
  boilerplates/airflow/files/tests/dags/test_dag_integrity.py
  boilerplates/airflow/init.sh
  boilerplates/airflow/sonar-project.properties
  boilerplates/airflow/templates/airflow.yaml
  boilerplates/airflow/templates/postgresql-persistent.yaml
  boilerplates/airflow/templates/service-account.yaml
  jenkins-slaves/airflow/Dockerfile.rhel7
  jenkins-slaves/airflow/README.md
  jenkins-slaves/airflow/contrib/bin/scl_enable
  jenkins-slaves/airflow/contrib/npmrc
  jenkins-slaves/airflow/ocp-config/Tailorfile
  jenkins-slaves/airflow/ocp-config/bc.yml
  jenkins-slaves/airflow/ocp-config/is.yml
  ocp-templates/templates/elasticsearch/elasticsearch-ephemeral-master-template.yaml
  ocp-templates/templates/elasticsearch/elasticsearch-ephemeral-node-template.yaml
  ocp-templates/templates/elasticsearch/elasticsearch-persistent-master-template.yaml
  ocp-templates/templates/elasticsearch/elasticsearch-persistent-node-template.yaml
  rundeck-jobs/quickstarts/airflow.yaml
Labels: enhancement

#323 switch to centos, volume/persistance enablement and extension management
  boilerplates/jupyter-notebook/files/docker/Dockerfile
  boilerplates/jupyter-notebook/files/docker/jupyter_notebook_config.json
  boilerplates/jupyter-notebook/files/docker/requirements.txt
  boilerplates/jupyter-notebook/files/docker/run.sh
Labels: bug

#324 fixes #295 for both jupyter-notebook and ds-ml-service
  boilerplates/ds-ml-service/Jenkinsfile
  boilerplates/ds-ml-service/files/docker/Dockerfile
  boilerplates/ds-ml-service/files/test/run_integration_tests.sh
  boilerplates/ds-ml-service/files/test/run_unittests.sh
  boilerplates/jupyter-notebook/files/docker/Dockerfile
Labels: enhancement
