Repository opendevstack/ods-project-quickstarters, pull requests merged in 2019-10, with the labels that each got.

#357 prepare jenkins slaves for 1.2.x release
  jenkins-slaves/nodejs10-angular/Dockerfile.rhel7
  jenkins-slaves/nodejs8-angular/Dockerfile.rhel7
  jenkins-slaves/python/Dockerfile.rhel7
Labels: bug

#363 fe-react: Make sure npm i is run within node docker image
  boilerplates/fe-react/init.sh
Labels: bug

#365 fe-react: Fix env var that define where test reports are generated
  boilerplates/fe-react/Jenkinsfile
Labels: bug

#367 be-python-flask: Use default test location folder instead of custom
  boilerplates/be-python-flask/Jenkinsfile
Labels: bug

#371 Unit test results ouptuts with Junit XML for Vue QS
  boilerplates/fe-vue/Jenkinsfile
  boilerplates/fe-vue/files/package.json
Labels: bug

#373 ds-ml-service mro ready
  boilerplates/ds-ml-service/Jenkinsfile
Labels: enhancement

#379 one liner sed append require line in karma conf
  boilerplates/fe-angular/init.sh
Labels: bug

#377 tag image stage for airflow cluster quickstarter
  boilerplates/airflow/Jenkinsfile
Labels: bug, enhancement

#386 adding sonarqube go plugin
  boilerplates/be-golang/sonar-project.properties
Labels: enhancement

#414 add pipeline config during mro creation / provisioning -> master
  boilerplates/release-manager/create-ocp-resources.sh
  ocp-templates/ocp-config/cd-docgen/cd-pipeline.yml
Labels: bug
